name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.9
        
    - name: Install build dependencies
      run: sudo apt-get install -y libblas-dev liblapack-dev gfortran
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      run: python main.py
      
    - name: Upload Markdown file
      uses: actions/upload-artifact@v2
      with:
        name: agenda_data
        path: output/agenda_data.md
